// assets/snapsort/src/svelte/Handle.svelte
<script lang="ts">
  import { getContext, onDestroy, onMount, type Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import type {
    Item,
  } from "@snap-engine/snapsort";

  type HandleProps = Omit<HTMLAttributes<HTMLDivElement>, "children"> & {
    children: Snippet;
    className?: string;
  };

  let {
    children,
    style = "",
    class: classValue = "",
    className = "",
    ...divProps
  }: HandleProps = $props();

  const item: Item | null = getContext("item");
  let handleElement: HTMLElement | null = null;
  const mergedClass = $derived(`snapsort-handle ${classValue} ${className}`.trim());

  onMount(() => {
    if (item && handleElement) {
      item.addInputAlias(handleElement);
    }
  });

  onDestroy(() => {
    if (item && handleElement) {
      item.removeInputAlias(handleElement);
    }
  });
</script>

<div
  {...divProps}
  class={mergedClass}
  bind:this={handleElement}
  {style}
>
  {@render children()}
</div>

<style>

</style>

// assets/snapsort/src/react/Handle.tsx
import {
  forwardRef,
  useContext,
  useEffect,
  useImperativeHandle,
  useRef,
  type HTMLAttributes,
  type ReactNode,
} from "react";
import { ItemObjectContext } from "./Item";

export interface HandleProps
  extends Omit<HTMLAttributes<HTMLDivElement>, "children"> {
  children: ReactNode;
  className?: string;
}

export const Handle = forwardRef<HTMLDivElement, HandleProps>(function Handle(
  { children, className = "", style, ...divProps },
  ref,
) {
  const item = useContext(ItemObjectContext);
  const handleRef = useRef<HTMLDivElement>(null);

  useImperativeHandle(ref, () => handleRef.current as HTMLDivElement, []);

  useEffect(() => {
    const handleElement = handleRef.current;
    if (!item || !handleElement) return;

    item.addInputAlias(handleElement);
    return () => {
      item.removeInputAlias(handleElement);
    };
  }, [item]);

  return (
    <div
      {...divProps}
      ref={handleRef}
      className={`snapsort-handle ${className}`.trim()}
      style={style}
    >
      {children}
    </div>
  );
});
