// assets/snapsort/src/svelte/Item.svelte
<script lang="ts">
  import { getContext, setContext, onDestroy, untrack } from "svelte";
  import { Item as SnapSortItem } from "@snap-engine/snapsort";
  import type {
    Container,
    ItemMetadata,
  } from "@snap-engine/snapsort";
  import type { Engine } from "@snap-engine/core";
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";

  type ItemProps = Omit<HTMLAttributes<HTMLDivElement>, "children"> & {
    children: Snippet;
    className?: string;
    item?: SnapSortItem | null;
    itemId?: string;
    metadata?: ItemMetadata;
    selected?: boolean;
  };

  let {
    children,
    itemId,
    style = "",
    class: classValue = "",
    className = "",
    item = $bindable<SnapSortItem | null>(null),
    metadata,
    selected,
    ...divProps
  }: ItemProps = $props();

  const engine: Engine = getContext("engine");
  const container: Container | null = getContext("container");
  const initial = untrack(() => ({ item, itemId, metadata, selected }));

  if (!container) {
    throw new Error("SnapSort Item: must be rendered inside a Container.");
  }
  if (initial.metadata && "itemId" in initial.metadata) {
    throw new Error("SnapSort Item: `metadata.itemId` was removed. Pass `itemId` as its own prop instead.");
  }
  if (initial.item == null && !initial.itemId) {
    throw new Error("SnapSort Item: missing required `itemId` prop.");
  }

  const ownsItem = initial.item == null;
  const resolvedItem = initial.item ?? new SnapSortItem(engine, container);
  const mergedClass = $derived(`snapsort-item ${classValue} ${className}`.trim());

  if (resolvedItem.engine !== engine) {
    throw new Error("SnapSort Item: the supplied `item` belongs to another Engine.");
  }
  const isCopyClone =
    !ownsItem &&
    resolvedItem.parent === null &&
    resolvedItem.rootContainer === container.rootContainer;
  if (!ownsItem && resolvedItem.parent !== container && !isCopyClone) {
    throw new Error(
      "SnapSort Item: the supplied `item` must already belong to the surrounding Container.",
    );
  }
  item = resolvedItem;
  setContext("item", resolvedItem);

  if (initial.itemId !== undefined) {
    resolvedItem.itemId = initial.itemId;
  }
  if (!resolvedItem.itemId) {
    throw new Error("SnapSort Item: missing required `itemId` prop.");
  }
  if (initial.metadata !== undefined) {
    resolvedItem.metadata = initial.metadata;
  }
  if (initial.selected !== undefined) {
    resolvedItem.selected = initial.selected;
  }

  $effect(() => {
    if (item !== resolvedItem) {
      throw new Error("SnapSort Item: the `item` prop cannot change after mount.");
    }
    if (itemId !== undefined) {
      resolvedItem.itemId = itemId;
    }
    if (metadata !== undefined) {
      if ("itemId" in metadata) {
        throw new Error("SnapSort Item: `metadata.itemId` was removed. Pass `itemId` as its own prop instead.");
      }
      resolvedItem.metadata = metadata;
    }
    if (selected !== undefined) {
      resolvedItem.selected = selected;
    }
  });

  function bindItemElement(element: HTMLDivElement) {
    resolvedItem.element = element;
    return {
      destroy() {
        resolvedItem.detachElement(element);
      },
    };
  }

  onDestroy(() => {
    if (ownsItem) {
      resolvedItem.destroy(false);
    }
  });
</script>

<div
  {...divProps}
  class={mergedClass}
  data-snapsort-item-id={resolvedItem.resolvedItemId}
  use:bindItemElement
  {style}
>
  {@render children()}
</div>

<style>
  .snapsort-item {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: var(--size-4);
    box-sizing: border-box;
  }
</style>

// assets/snapsort/src/react/Item.tsx
import {
  createContext,
  forwardRef,
  useCallback,
  useContext,
  useEffect,
  useImperativeHandle,
  useRef,
  type HTMLAttributes,
  type ReactNode,
} from "react";
import { Item as ItemObject, type ItemMetadata } from "@snap-engine/snapsort";
import { useSnapSortEngine } from "./Engine";
import { ContainerObjectContext } from "./Container";

export const ItemObjectContext = createContext<ItemObject | null>(null);

export interface ItemProps
  extends Omit<HTMLAttributes<HTMLDivElement>, "children"> {
  children: ReactNode;
  className?: string;
  item?: ItemObject | null;
  itemId?: string;
  metadata?: ItemMetadata;
  /** Consumer-owned selection flag — see `Item.selected` in `@snap-engine/snapsort`. */
  selected?: boolean;
}

export const Item = forwardRef<ItemObject, ItemProps>(function SnapSortItem(
  {
    children,
    className = "",
    item: providedItem = null,
    itemId,
    metadata,
    selected,
    style,
    ...divProps
  },
  ref,
) {
  const engine = useSnapSortEngine();
  const container = useContext(ContainerObjectContext);
  const itemDomRef = useRef<HTMLDivElement>(null);
  const initialProvidedItemRef = useRef<ItemObject | null>(providedItem);
  const ownsItemRef = useRef(providedItem == null);
  const itemRef = useRef<ItemObject | null>(providedItem);
  if (!container) {
    throw new Error("SnapSort Item: must be rendered inside a Container.");
  }
  if (providedItem !== initialProvidedItemRef.current) {
    throw new Error(
      "SnapSort Item: the `item` prop cannot change after mount.",
    );
  }
  if (metadata && "itemId" in metadata) {
    throw new Error(
      "SnapSort Item: `metadata.itemId` was removed. Pass `itemId` as its own prop instead.",
    );
  }
  if (ownsItemRef.current && !itemId) {
    throw new Error("SnapSort Item: missing required `itemId` prop.");
  }
  if (!itemRef.current) {
    itemRef.current = new ItemObject(engine, null);
  }
  const item = itemRef.current;
  if (item.engine !== engine) {
    throw new Error(
      "SnapSort Item: the supplied `item` belongs to another Engine.",
    );
  }
  const isCopyClone =
    !ownsItemRef.current &&
    item.parent === null &&
    item.rootContainer === container.rootContainer;
  if (!ownsItemRef.current && item.parent !== container && !isCopyClone) {
    throw new Error(
      "SnapSort Item: the supplied `item` must already belong to the surrounding Container.",
    );
  }
  if (itemId !== undefined) {
    item.itemId = itemId;
  }
  if (!item.itemId) {
    throw new Error("SnapSort Item: missing required `itemId` prop.");
  }
  if (metadata !== undefined) {
    item.metadata = metadata;
  }
  if (selected !== undefined) {
    item.selected = selected;
  }

  useImperativeHandle(ref, () => item, [item]);

  const setItemElement = useCallback(
    (element: HTMLDivElement | null) => {
      const previousElement = itemDomRef.current;
      itemDomRef.current = element;
      if (element) {
        item.element = element;
      } else if (previousElement) {
        item.detachElement(previousElement);
      }
    },
    [item],
  );

  useEffect(() => {
    if (ownsItemRef.current && item.parent !== container) {
      container.addItem(item);
    } else if (
      item.parent === container &&
      !container.itemOrderedList.includes(item)
    ) {
      container.addItem(item);
    }
    return () => {
      if (ownsItemRef.current) {
        item.destroy(false);
      }
    };
  }, [container, item]);

  return (
    <ItemObjectContext.Provider value={item}>
      <div
        {...divProps}
        ref={setItemElement}
        className={`snapsort-item ${className}`.trim()}
        data-snapsort-item-id={item.resolvedItemId}
        style={{
          alignItems: "center",
          boxSizing: "border-box",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          padding: 4,
          ...style,
        }}
      >
        {children}
      </div>
    </ItemObjectContext.Provider>
  );
});
