// assets/snapline/svelte/src/EdgeSync.svelte
<script lang="ts">
  import {
    EdgeSyncController,
    type ConnectorMirror,
    type EdgeConnectIntentEvent,
    type EdgeDisconnectIntentEvent,
    type EdgeEndpoint,
    type EdgeLike,
  } from "@snap-engine/snapline";
  import type { Engine } from "@snap-engine/core";
  import { getContext, onDestroy, tick } from "svelte";

  let {
    edges,
    identity,
    onEdgeConnect = undefined,
    onEdgeDisconnect = undefined,
  }: {
    /** The consumer's edge document — the single source of truth. */
    edges: readonly EdgeLike[];
    /** Maps a connector to its semantic endpoint, or null for unmanaged connectors. */
    identity: (connector: ConnectorMirror) => EdgeEndpoint | null;
    onEdgeConnect?: ((event: EdgeConnectIntentEvent) => void) | undefined;
    onEdgeDisconnect?: ((event: EdgeDisconnectIntentEvent) => void) | undefined;
  } = $props();

  let engine: Engine = getContext("engine");

  const controller = new EdgeSyncController({
    engine,
    identity: (connector) => identity(connector),
    // $props getters keep this read live — sync always sees the current doc.
    getEdges: () => edges,
    callbacks: {
      // Gesture intents fire synchronously inside the drop dispatch; the
      // consumer writes its document in the handler. Reconciling in a
      // microtask keeps the accept AND reject paths inside the same task —
      // before the browser paints — without re-entering the gesture stack.
      onEdgeConnect: (event) => {
        onEdgeConnect?.(event);
        queueMicrotask(() => controller.sync());
      },
      onEdgeDisconnect: (event) => {
        onEdgeDisconnect?.(event);
        queueMicrotask(() => controller.sync());
      },
    },
  });

  // Doc changes (presets, programmatic edits, node mounts) reconcile after
  // tick so freshly mounted connectors are registered before lines hydrate.
  $effect(() => {
    void edges;
    void tick().then(() => controller.sync());
  });

  onDestroy(() => controller.dispose());
</script>

// assets/snapline/react/src/EdgeSync.tsx
import {
  EdgeSyncController,
  type ConnectorMirror,
  type EdgeConnectIntentEvent,
  type EdgeDisconnectIntentEvent,
  type EdgeEndpoint,
  type EdgeLike,
} from "@snap-engine/snapline";
import { useEffect, useRef } from "react";
import { useSnapLineEngine } from "./Engine";

export interface EdgeSyncProps {
  /** The consumer's edge document — the single source of truth. */
  edges: readonly EdgeLike[];
  /** Maps a connector to its semantic endpoint, or null for unmanaged connectors. */
  identity: (connector: ConnectorMirror) => EdgeEndpoint | null;
  onEdgeConnect?: (event: EdgeConnectIntentEvent) => void;
  onEdgeDisconnect?: (event: EdgeDisconnectIntentEvent) => void;
}

export function EdgeSync({
  edges,
  identity,
  onEdgeConnect,
  onEdgeDisconnect,
}: EdgeSyncProps) {
  const engine = useSnapLineEngine();
  const propsRef = useRef({ edges, identity, onEdgeConnect, onEdgeDisconnect });
  propsRef.current = { edges, identity, onEdgeConnect, onEdgeDisconnect };
  const controllerRef = useRef<EdgeSyncController | null>(null);

  useEffect(() => {
    const controller = new EdgeSyncController({
      engine,
      identity: (connector) => propsRef.current.identity(connector),
      getEdges: () => propsRef.current.edges,
      callbacks: {
        // For same-frame reconciliation of gesture intents, write the edge
        // document inside flushSync in the handler; the microtask sync then
        // sees the fresh document before paint. Deferred stores degrade to a
        // one-frame pending state, never an inconsistent one.
        onEdgeConnect: (event) => {
          propsRef.current.onEdgeConnect?.(event);
          queueMicrotask(() => controller.sync());
        },
        onEdgeDisconnect: (event) => {
          propsRef.current.onEdgeDisconnect?.(event);
          queueMicrotask(() => controller.sync());
        },
      },
    });
    controllerRef.current = controller;
    controller.sync();
    return () => {
      controller.dispose();
      if (controllerRef.current === controller) controllerRef.current = null;
    };
  }, [engine]);

  useEffect(() => {
    controllerRef.current?.sync();
  }, [edges]);

  return null;
}
