// demo/svelte/src/lib/node_ui/Select.svelte

<script lang="ts">
    import { RectSelectComponent, SnapLine } from "../../../../../src/index";
    import { onMount, getContext } from "svelte";

    let selectDOM: HTMLDivElement | null = null;
    let engine:SnapLine = getContext("engine");
    let select = new RectSelectComponent(engine.global, null);

    onMount(() => {
        select.element = selectDOM as HTMLElement;
    });
    
</script>

<div id="select-container" bind:this={selectDOM}></div>

<style>
    #select-container {
        position: absolute;
        top: 0;
        left: 0;
        width: 0;
        height: 0;
        background-color: rgba(0, 0, 0, 0.103);
    }
</style>

// assets/snapline/react/src/Select.tsx
import { useLayoutEffect, useRef, type CSSProperties } from "react";
import { RectSelectComponent, type SelectCallbacks } from "@snap-engine/snapline";
import { useSnapLineEngine } from "./Engine";

export interface SelectProps {
  className?: string;
  id?: string;
  style?: CSSProperties;
  callbacks?: SelectCallbacks;
}

export function Select({
  className,
  id = "select-container",
  style,
  callbacks = {},
}: SelectProps) {
  const engine = useSnapLineEngine();
  const selectRef = useRef<RectSelectComponent | null>(null);
  const selectDomRef = useRef<HTMLDivElement>(null);

  if (!selectRef.current) {
    selectRef.current = new RectSelectComponent(engine, null, { callbacks });
  }
  const select = selectRef.current;

  useLayoutEffect(() => {
    const unbind = select.bindGeometryWriter((rect) => {
      const element = selectDomRef.current;
      if (!element) return;
      element.style.display = rect.visible ? "block" : "none";
      element.style.width = `${rect.width}px`;
      element.style.height = `${rect.height}px`;
      element.style.transform = `translate3d(${rect.x}px, ${rect.y}px, 0)`;
    });
    return () => {
      unbind();
      select.destroy(false);
    };
  }, [select]);

  return (
    <div
      id={id}
      ref={selectDomRef}
      className={className}
      data-snapline-type="selection"
      style={{
        backgroundColor: "rgba(0, 0, 0, 0.103)",
        position: "absolute",
        top: 0,
        left: 0,
        transformOrigin: "top left",
        pointerEvents: "none",
        display: "none",
        width: 0,
        height: 0,
        transform: "translate3d(0px, 0px, 0)",
        ...style,
      }}
    />
  );
}
