// assets/snapline/svelte/src/Select.svelte
<script lang="ts">
    import { RectSelectComponent, type SelectCallbacks, type SelectRect } from "@snap-engine/snapline";
    import type { Engine } from "@snap-engine/core";
    import { onDestroy, getContext } from "svelte";

    let { className = "", callbacks = {} }: { className?: string; callbacks?: SelectCallbacks } = $props();

    let engine: Engine = getContext("engine");
    let select = new RectSelectComponent(engine, null, { callbacks });

    // The selection box is framework-rendered: core reports the world-space rect
    // via onRectChange and this state draws it, so consumers can restyle or
    // replace the box entirely (override #select-container / pass a class).
    let rect = $state<SelectRect>({ x: 0, y: 0, width: 0, height: 0, visible: false });
    select.callbacks.onRectChange = (r: SelectRect) => {
        rect = r;
    };

    onDestroy(() => {
        select.destroy();
    });

    export function getSelectObject() {
        return select;
    }
</script>

<div
    id="select-container"
    data-snapline-type="selection"
    class={className}
    style:display={rect.visible ? "block" : "none"}
    style:width={`${rect.width}px`}
    style:height={`${rect.height}px`}
    style:transform={`translate3d(${rect.x}px, ${rect.y}px, 0)`}
></div>

<style>
    #select-container {
        position: absolute;
        top: 0;
        left: 0;
        width: 0;
        height: 0;
        transform-origin: top left;
        pointer-events: none;
        background-color: rgba(0, 0, 0, 0.103);
    }
</style>

// assets/snapline/react/src/Select.tsx
import { useEffect, useRef, useState, type CSSProperties } from "react";
import { RectSelectComponent, type SelectCallbacks, type SelectRect } from "@snap-engine/snapline";
import { useSnapLineEngine } from "./Engine";

export interface SelectProps {
  className?: string;
  id?: string;
  style?: CSSProperties;
  callbacks?: SelectCallbacks;
}

export function Select({
  className,
  id = "select-container",
  style,
  callbacks = {},
}: SelectProps) {
  const engine = useSnapLineEngine();
  const selectRef = useRef<RectSelectComponent | null>(null);

  if (!selectRef.current) {
    selectRef.current = new RectSelectComponent(engine, null, { callbacks });
  }
  const select = selectRef.current;

  // The selection box is framework-rendered: core reports the world-space rect
  // via onRectChange and this state draws it, so consumers can restyle or
  // replace the box (className/style props).
  const [rect, setRect] = useState<SelectRect>({
    x: 0,
    y: 0,
    width: 0,
    height: 0,
    visible: false,
  });

  useEffect(() => {
    select.callbacks.onRectChange = (r: SelectRect) => setRect(r);
    return () => {
      select.destroy();
    };
  }, [select]);

  return (
    <div
      id={id}
      className={className}
      data-snapline-type="selection"
      style={{
        backgroundColor: "rgba(0, 0, 0, 0.103)",
        position: "absolute",
        top: 0,
        left: 0,
        transformOrigin: "top left",
        pointerEvents: "none",
        display: rect.visible ? "block" : "none",
        width: `${rect.width}px`,
        height: `${rect.height}px`,
        transform: `translate3d(${rect.x}px, ${rect.y}px, 0)`,
        ...style,
      }}
    />
  );
}
