// demo/svelte/src/component/lib/Node.svelte
<script lang="ts">
    import { NodeComponent, LineComponent } from "../../lib/snapline.mjs";
    import Line from "./Line.svelte";
    import { onMount } from "svelte";
    let { nodeObject, className, children}: { nodeObject: NodeComponent, className: string, children: any} = $props();
    let nodeDOM: HTMLDivElement | null = null;
    let lineList: LineComponent[] = $state(nodeObject.getAllLines());

    let formattedLines = $derived(lineList.map(line => ({
        x_start: line.x_start,
        y_start: line.y_start,
        x_end: line.x_end,
        y_end: line.y_end
    })));

    let nodeStyle = $state(nodeObject.getNodeStyle());

    function updateNodeStyle(style: any) {
        nodeStyle = style;
        if (nodeDOM) {
            nodeDOM.style.transform = style.transform;
            nodeDOM.style.position = "absolute";
            nodeDOM.style.transformOrigin = "top left";
        }
    }

    onMount(() => {
        nodeObject.setRenderNodeCallback(updateNodeStyle);
        nodeObject.setRenderLinesCallback(() => {
            lineList = nodeObject.getAllLines();
        });
        nodeObject.init(nodeDOM);
    });
    
</script>

{#each formattedLines as line}
    <Line {line} />
{/each}
<div bind:this={nodeDOM} data-snapline-state={nodeStyle._focus ? "focus" : "idle"} class={className}>
    {@render children()}
</div>


<style>

</style>

// demo/react/src/components/lib/Node.jsx
import React from "react";
import { useState } from "react";
import { useRef } from "react";
import { useEffect } from "react";
import Line from "./Line";

export default function Node({ nodeObject, children }) {
  let node = useRef(nodeObject);
  let [nodeStyle, setNodeStyle] = useState(node.current.getNodeStyle());
  let [lineList, setLineList] = useState(node.current.getAllLines());

  let nodeDom = useRef(null);

  const updateNodeStyle = (style) => {
    setNodeStyle(style);
    nodeDom.current.style.transform = style.transform;
    nodeDom.current.style.position = "absolute";
    nodeDom.current.style.transformOrigin = "top left";
  };

  useEffect(() => {
    node.current.setRenderNodeCallback(updateNodeStyle);
    node.current.setRenderLinesCallback(() => {
      let lines = node.current.getAllLines();
      setLineList(lines);
    });
    node.current.init(nodeDom.current);
  }, []);

  return (
    <>
      {lineList.map((line, index) => (
        <Line key={index} line={line} />
      ))}

      <div
        className={"sl-node"}
        data-snapline-state={nodeStyle["_focus"] ? "focus" : "idle"}
        ref={nodeDom}
        // style={nodeStyle}
      >
        {children}
      </div>
    </>
  );
}
