// assets/snapline/react/src/Line.tsx
import { useEffect, useRef, useState, type CSSProperties } from "react";
import type { LineComponent } from "@snap-engine/snapline";

export interface LineProps {
  line: LineComponent;
  className?: string;
  pathClassName?: string;
  pathStyle?: CSSProperties;
  showArrow?: boolean;
  data?: Record<string, string>;
}

interface LineState {
  style: CSSProperties;
  x1: number;
  x2: number;
  x3: number;
  y1: number;
  y2: number;
  y3: number;
}

function getLineState(line: LineComponent): LineState {
  const dx = line.endWorldX - line.worldTransform.x;
  const dy = line.endWorldY - line.worldTransform.y;
  return {
    style: {
      overflow: "visible",
      pointerEvents: "none",
      position: "absolute",
      transform: `translate3d(${line.worldTransform.x}px, ${line.worldTransform.y}px, 0)`,
      willChange: "transform",
      zIndex: 1000,
    },
    x1: Math.abs(dx / 2),
    y1: 0,
    x2: dx - Math.abs(dx / 2),
    y2: dy,
    x3: dx,
    y3: dy,
  };
}

export function Line({
  line,
  className,
  pathClassName = "sl-connector-line",
  pathStyle,
  showArrow = true,
  data = {},
}: LineProps) {
  const lineDomRef = useRef<SVGSVGElement>(null);
  const [lineState, setLineState] = useState<LineState>(() =>
    getLineState(line),
  );

  useEffect(() => {
    if (lineDomRef.current) {
      line.element = lineDomRef.current as unknown as HTMLElement;
    }
    const renderLine = () => {
      setLineState(getLineState(line));
    };
    const cleanup = line.onRender(renderLine);
    renderLine();
    return cleanup;
  }, [line]);

  return (
    <svg
      data-snapline-type="connector-line"
      className={className}
      {...Object.fromEntries(
        Object.entries(data).map(([key, value]) => [`data-${key}`, value]),
      )}
      height="4"
      ref={lineDomRef}
      style={lineState.style}
      width="4"
    >
      <path
        className={pathClassName}
        d={`M 0,0 C ${lineState.x1}, ${lineState.y1} ${lineState.x2}, ${lineState.y2} ${lineState.x3}, ${lineState.y3}`}
        markerEnd={showArrow ? `url(#arrow-${line.id})` : undefined}
        style={{
          fill: "none",
          stroke: "#545454",
          strokeLinecap: "round",
          strokeLinejoin: "round",
          strokeWidth: 4,
          ...pathStyle,
        }}
      />
      {showArrow ? (
        <marker id={`arrow-${line.id}`} viewBox="0 0 24 24" refX="0" refY="12" orient="auto">
          <polygon points="4,4 20,12 4,22" fill="#545454" />
        </marker>
      ) : null}
    </svg>
  );
}

// demo/svelte/src/lib/node_ui/Line.svelte
<script lang="ts">
    import type { LineComponent } from "../../../../../src/index";
    import { onMount } from "svelte";
    let { line }: { line: LineComponent } = $props();

    let style = $state("position: absolute; overflow: visible; pointer-events: none; will-change: transform; transform: translate3d(0px, 0px, 0);");
    let dx = $state(0);
    let dy = $state(0);
    let x0 = $state(line.transform.x);
    let y0 = $state(line.transform.y);
    let x1 = $state(0);
    let y1 = $state(0);
    let x2 = $state(0);
    let y2 = $state(0);
    let x3 = $state(0);
    let y3 = $state(0);

    function renderLine() {
      const thisLine: LineComponent = line;
      x0 = thisLine.transform.x;
      y0 = thisLine.transform.y;
      style = `position: absolute; overflow: visible; pointer-events: none; will-change: transform; transform: translate3d(${x0}px, ${y0}px, 0);`;
      dx = thisLine.endWorldX - thisLine.transform.x;
      dy = thisLine.endWorldY - thisLine.transform.y;
        x1 = Math.abs(dx / 2);
        y1 = 0;
        x2 = dx - Math.abs(dx / 2);
        y2 = dy;
        x3 = dx;
        y3 = dy;
    }

    let lineDOM: SVGElement | null = null; 

  onMount(() => {
    line.element = (lineDOM as unknown as HTMLElement);
    line.callback.afterWrite2 = renderLine;
  });
</script>

<svg
  data-snapline-type="connector-line"
  width="4"
  height="4"
  style={style}
  bind:this={lineDOM}
>
  <path
    class="sl-connector-line"
    d={`M 0,0 C ${x1}, ${y1} ${x2}, ${y2} ${x3}, ${y3}`}
    marker-end="url(#arrow)"
  />
  <marker id="arrow" viewBox="0 0 24 24" refX="0" refY="12" orient="auto">
    <polygon points="4,4 20,12 4,22" fill="#545454"/>
  </marker>
</svg>

<style>
  svg {
    z-index: 1000;
  }
  path {
    fill: none;
    stroke: #545454;
    stroke-width: 4;
    stroke-linecap: round;
    stroke-linejoin: round;
  }
</style>
