// assets/snapline/react/src/Node.tsx
import {
  createContext,
  forwardRef,
  useLayoutEffect,
  useContext,
  useImperativeHandle,
  useRef,
  useState,
  type ComponentType,
  type CSSProperties,
  type HTMLAttributes,
  type RefCallback,
  type ReactNode,
} from "react";
import {
  DEFAULT_RESIZE_HANDLE_THICKNESS,
  LineMirror,
  NodeMirror,
  type ResizeHandle,
  type NewLineResolver,
  type NodeCallbacks,
  type GeometryChangeEvent,
  type NodeResizeEvent,
  type SnapLineMetadata,
} from "@snap-engine/snapline";
import { useSnapLineEngine } from "./Engine";
import { Line } from "./Line";

export const NodeMirrorContext = createContext<NodeMirror | null>(null);

export interface NodeProps {
  /** Stable domain identity; minted when omitted (supply for persistence). */
  id?: string;
  children: ReactNode;
  className?: string;
  /** One renderer for every line leaving this node. */
  lineComponent?: ComponentType<{ line: LineMirror }>;
  /**
   * Picks a renderer per line, so a data edge and a control edge leaving the
   * same node can look different. Falls back to `lineComponent` when it
   * returns nothing.
   *
   * Resolved at render time, not at line creation: hydration never runs the
   * creation callback (a reloaded graph builds its lines through the
   * reconciler), so resolving from the line is what makes a line you just drew
   * and the same line after a refresh render identically. Branch on
   * serializable data you put in the payload — never store a component
   * reference in a record.
   */
  resolveLineComponent?: (
    line: LineMirror,
  ) => ComponentType<{ line: LineMirror }> | null | undefined;
  /** Seeds application data onto a line a drag from this node creates. */
  resolveNewLine?: NewLineResolver;
  nodeObject?: NodeMirror | null;
  style?: CSSProperties;
  x?: number;
  y?: number;
  width?: number;
  height?: number;
  resizable?: boolean;
  minWidth?: number;
  minHeight?: number;
  resizeHandleThickness?: number;
  resizeHandles?: true | readonly ResizeHandle[];
  resizeCursors?: Partial<Record<ResizeHandle, string>>;
  metadata?: SnapLineMetadata;
  callbacks?: NodeCallbacks;
  edgePan?: boolean;
  onGeometryCommit?: (event: GeometryChangeEvent) => void;
  onSizeChange?: (event: NodeResizeEvent) => void;
  /** Framework-native attributes and events for the outer node element. */
  elementProps?: HTMLAttributes<HTMLDivElement>;
}

export const Node = forwardRef<NodeMirror, NodeProps>(function Node(
  {
    id,
    children,
    className = "",
    lineComponent: LineRenderer = Line,
    resolveLineComponent,
    resolveNewLine,
    nodeObject = null,
    style,
    x = 0,
    y = 0,
    width,
    height,
    resizable = false,
    minWidth,
    minHeight,
    resizeHandleThickness,
    resizeHandles,
    resizeCursors,
    metadata = {},
    callbacks = {},
    edgePan = true,
    onGeometryCommit,
    onSizeChange,
    elementProps,
  },
  ref,
) {
  const engine = useSnapLineEngine();
  const nodeDomRef = useRef<HTMLDivElement>(null);
  const ownsNodeRef = useRef(nodeObject == null);
  const nodeRef = useRef<NodeMirror | null>(nodeObject);
  if (!nodeRef.current) {
    nodeRef.current = new NodeMirror(engine, null, {
      id,
      resizable,
      minWidth,
      minHeight,
      resizeHandleThickness,
      resizeHandles,
      resizeCursors,
      metadata,
      callbacks: {},
      edgePan,
      resolveNewLine,
    });
  }
  const node = nodeRef.current;
  const [lineList, setLineList] = useState<LineMirror[]>(
    node.getAllOutgoingLines(),
  );
  const latestRef = useRef({
    callbacks,
    onGeometryCommit,
    onSizeChange,
  });
  latestRef.current = {
    callbacks,
    onGeometryCommit,
    onSizeChange,
  };

  useImperativeHandle(ref, () => node, [node]);

  useLayoutEffect(() => {
    if (nodeDomRef.current) {
      node.element = nodeDomRef.current;
      node.remeasureDomGeometry();
    }
    const original = { ...node.callbacks };
    const invoke = <Event,>(
      event: Event,
      ...handlers: Array<((value: Event) => unknown) | undefined>
    ): void => {
      const seen = new Set<Function>();
      for (const handler of handlers) {
        if (!handler || seen.has(handler)) continue;
        seen.add(handler);
        handler(event);
      }
    };
    node.callbacks.canStartDrag = (event) => {
      const handlers = [
        original.canStartDrag,
        latestRef.current.callbacks.canStartDrag,
      ];
      const seen = new Set<Function>();
      for (const handler of handlers) {
        if (!handler || seen.has(handler)) continue;
        seen.add(handler);
        if (handler(event) === false) return false;
      }
      return true;
    };
    node.callbacks.resolveDragPosition = (event) =>
      latestRef.current.callbacks.resolveDragPosition?.(event) ??
      original.resolveDragPosition?.(event) ??
      { x: event.x, y: event.y };
    node.callbacks.resolveSelectionMode = (event) =>
      latestRef.current.callbacks.resolveSelectionMode?.(event) ??
      original.resolveSelectionMode?.(event) ??
      "replace";
    node.callbacks.onDragStart = (event) =>
      invoke(
        event,
        original.onDragStart,
        latestRef.current.callbacks.onDragStart,
      );
    node.callbacks.onDrag = (event) =>
      invoke(event, original.onDrag, latestRef.current.callbacks.onDrag);
    node.callbacks.onSelectionChange = (event) =>
      invoke(
        event,
        original.onSelectionChange,
        latestRef.current.callbacks.onSelectionChange,
      );
    node.callbacks.onResizeHandleChange = (event) =>
      invoke(
        event,
        original.onResizeHandleChange,
        latestRef.current.callbacks.onResizeHandleChange,
      );
    node.callbacks.onLinesChanged = (event) => {
      invoke(
        event,
        original.onLinesChanged,
        latestRef.current.callbacks.onLinesChanged,
      );
      setLineList([...event.lines]);
    };
    node.callbacks.onSizeChange = (event) => {
      invoke(
        event,
        original.onSizeChange,
        latestRef.current.callbacks.onSizeChange,
        latestRef.current.onSizeChange,
      );
    };
    node.callbacks.onGeometryCommit = (event) =>
      invoke(
        event,
        original.onGeometryCommit,
        latestRef.current.callbacks.onGeometryCommit,
        latestRef.current.onGeometryCommit,
      );
    setLineList([...node.getAllOutgoingLines()]);
    const boundElement = nodeDomRef.current;

    return () => {
      node.callbacks.canStartDrag = original.canStartDrag;
      node.callbacks.resolveDragPosition = original.resolveDragPosition;
      node.callbacks.resolveSelectionMode = original.resolveSelectionMode;
      node.callbacks.onDragStart = original.onDragStart;
      node.callbacks.onDrag = original.onDrag;
      node.callbacks.onGeometryCommit = original.onGeometryCommit;
      node.callbacks.onSelectionChange = original.onSelectionChange;
      node.callbacks.onResizeHandleChange = original.onResizeHandleChange;
      node.callbacks.onLinesChanged = original.onLinesChanged;
      node.callbacks.onSizeChange = original.onSizeChange;
      if (ownsNodeRef.current) {
        node.destroy(false);
      } else if (boundElement) {
        node.detachElement(boundElement);
      }
    };
  }, [node]);

  useLayoutEffect(() => {
    node.worldTransform = { x, y };
    node.writeTransformAndLines();
  }, [node, x, y]);

  useLayoutEffect(() => {
    if (!node.element || (width == null && height == null)) return;
    const nextWidth = width ?? node.hitBox.width;
    const nextHeight = height ?? node.hitBox.height;
    if (width != null) node.element.style.width = `${width}px`;
    if (height != null) node.element.style.height = `${height}px`;
    node.setSizeState(nextWidth, nextHeight);
    node.remeasureDomGeometry();
  }, [node, width, height]);

  const handleSize =
    resizeHandleThickness ?? DEFAULT_RESIZE_HANDLE_THICKNESS;
  return (
    <NodeMirrorContext.Provider value={node}>
      {lineList.map((line) => (
        <LineForLine
          key={line.lineId}
          line={line}
          resolve={resolveLineComponent}
          fallback={LineRenderer}
        />
      ))}
      <div
        {...elementProps}
        ref={nodeDomRef}
        data-snapline-type="node"
        className={className}
        style={{
          position: "absolute",
          transformOrigin: "top left",
          willChange: "transform",
          ...(width != null ? { width: `${width}px` } : null),
          ...(height != null ? { height: `${height}px` } : null),
          ...style,
        }}
      >
        {children}
        {node.resizeHandles.map((handle) => (
          <div
            key={handle}
            data-snapline-part="node-resize"
            data-handle={handle}
            style={{
              position: "absolute",
              pointerEvents: "none",
              ...(handle === "n" || handle === "s"
                ? { left: handleSize, right: handleSize, height: handleSize }
                : null),
              ...(handle === "e" || handle === "w"
                ? { top: handleSize, bottom: handleSize, width: handleSize }
                : null),
              ...(handle.length === 2
                ? { width: handleSize, height: handleSize }
                : null),
              ...(handle.startsWith("n") ? { top: -handleSize / 2 } : null),
              ...(handle.startsWith("s") ? { bottom: -handleSize / 2 } : null),
              ...(handle.endsWith("e") ? { right: -handleSize / 2 } : null),
              ...(handle.endsWith("w") ? { left: -handleSize / 2 } : null),
            }}
          />
        ))}
      </div>
    </NodeMirrorContext.Provider>
  );
});

/** Callback ref for declaring any descendant as a node drag surface. */
export function useNodeHandle(): RefCallback<HTMLElement> {
  const node = useContext(NodeMirrorContext);
  const cleanup = useRef<(() => void) | null>(null);
  return (element) => {
    cleanup.current?.();
    cleanup.current = element && node ? node.registerDragHandle(element) : null;
  };
}

/** Per-line renderer resolution, evaluated at render time. */
function LineForLine({
  line,
  resolve,
  fallback: Fallback,
}: {
  line: LineMirror;
  resolve?: (
    line: LineMirror,
  ) => ComponentType<{ line: LineMirror }> | null | undefined;
  fallback: ComponentType<{ line: LineMirror }>;
}) {
  const Resolved = resolve?.(line) ?? Fallback;
  return <Resolved line={line} />;
}

// assets/snapline/svelte/src/Node.svelte
<script lang="ts">
    import { NodeMirror, LineMirror, DEFAULT_RESIZE_HANDLE_THICKNESS, type NodeCallbacks, type NewLineResolver, type GeometryChangeEvent, type NodeResizeEvent, type ResizeHandle, type SnapLineMetadata } from "@snap-engine/snapline";
    import type { Engine } from "@snap-engine/core";
    import Line from "./Line.svelte";
    import { onMount, setContext, getContext, onDestroy, tick, untrack } from "svelte";
    import type { HTMLAttributes } from "svelte/elements";
    import { blur } from "svelte/transition";

    let {
        id = undefined,
        className = "",
        LineSvelteComponent = Line,
        resolveLineComponent = undefined,
        resolveNewLine = undefined,
        nodeObject = null,
        x = 0,
        y = 0,
        width = undefined,
        height = undefined,
        resizable = false,
        minWidth = undefined,
        minHeight = undefined,
        resizeHandleThickness = undefined,
        resizeHandles = undefined,
        resizeCursors = undefined,
        metadata = {},
        callbacks = {},
        edgePan = true,
        onGeometryCommit = undefined,
        onSizeChange = undefined,
        elementProps = {},
        children,
    }: {
        /** Stable domain identity; minted when omitted (supply for persistence). */
        id?: string;
        className?: string;
        /** One renderer for every line leaving this node. */
        LineSvelteComponent?: typeof Line;
        /**
         * Picks a renderer per line, so a data edge and a control edge leaving
         * the same node can look different. Falls back to
         * `LineSvelteComponent` when it returns nothing.
         *
         * Resolved at render time, not at line creation: hydration never runs
         * the creation callback (a reloaded graph builds its lines through the
         * reconciler), so resolving from the line is what makes a line you just
         * drew and the same line after a refresh render identically. Branch on
         * serializable data you put in the payload — never store a component
         * reference in a record.
         */
        resolveLineComponent?: (line: LineMirror) => typeof Line | null | undefined;
        /** Seeds application data onto a line a drag from this node creates. */
        resolveNewLine?: NewLineResolver;
        nodeObject?: NodeMirror | null;
        x?: number;
        y?: number;
        width?: number;
        height?: number;
        resizable?: boolean;
        minWidth?: number;
        minHeight?: number;
        resizeHandleThickness?: number;
        resizeHandles?: true | readonly ResizeHandle[];
        resizeCursors?: Partial<Record<ResizeHandle, string>>;
        metadata?: SnapLineMetadata;
        callbacks?: NodeCallbacks;
        edgePan?: boolean;
        onGeometryCommit?: (event: GeometryChangeEvent) => void;
        onSizeChange?: (event: NodeResizeEvent) => void;
        /** Framework-native attributes and events for the outer node element. */
        elementProps?: HTMLAttributes<HTMLDivElement>;
        children: any;
    } = $props();
    let nodeDOM: HTMLDivElement | null = null;
    let engine: Engine = getContext("engine");
    const ownsNode = nodeObject == null;
    if (!nodeObject) {
         nodeObject = new NodeMirror(engine, null, { id, resizable, minWidth, minHeight, resizeHandleThickness, resizeHandles, resizeCursors, metadata, callbacks: {}, edgePan, resolveNewLine });
    }
    let lineList: LineMirror[] = $state(nodeObject.getAllOutgoingLines());

    let mounted = $state(false);
    let originalCallbacks: NodeCallbacks = {};

    function invoke<Event>(
        event: Event,
        ...handlers: Array<((value: Event) => unknown) | undefined>
    ) {
        const seen = new Set<Function>();
        for (const handler of handlers) {
            if (!handler || seen.has(handler)) continue;
            seen.add(handler);
            handler(event);
        }
    }

    setContext("nodeObject", nodeObject);

    onMount(() => {
        mounted = true;
        nodeObject.worldTransform = { x, y };
        nodeObject.element = nodeDOM as HTMLElement;
        nodeObject.writeTransform();
        originalCallbacks = { ...nodeObject.callbacks };
        nodeObject.callbacks.canStartDrag = (event) => {
            const handlers = [originalCallbacks.canStartDrag, callbacks.canStartDrag];
            const seen = new Set<Function>();
            for (const handler of handlers) {
                if (!handler || seen.has(handler)) continue;
                seen.add(handler);
                if (handler(event) === false) return false;
            }
            return true;
        };
        nodeObject.callbacks.resolveDragPosition = (event) =>
            callbacks.resolveDragPosition?.(event) ??
            originalCallbacks.resolveDragPosition?.(event) ??
            { x: event.x, y: event.y };
        nodeObject.callbacks.resolveSelectionMode = (event) =>
            callbacks.resolveSelectionMode?.(event) ??
            originalCallbacks.resolveSelectionMode?.(event) ??
            "replace";
        nodeObject.callbacks.onDragStart = (event) =>
            invoke(event, originalCallbacks.onDragStart, callbacks.onDragStart);
        nodeObject.callbacks.onDrag = (event) =>
            invoke(event, originalCallbacks.onDrag, callbacks.onDrag);
        nodeObject.callbacks.onSelectionChange = (event) =>
            invoke(event, originalCallbacks.onSelectionChange, callbacks.onSelectionChange);
        nodeObject.callbacks.onResizeHandleChange = (event) =>
            invoke(event, originalCallbacks.onResizeHandleChange, callbacks.onResizeHandleChange);
        nodeObject.callbacks.onGeometryCommit = (event) =>
            invoke(event, originalCallbacks.onGeometryCommit, callbacks.onGeometryCommit, onGeometryCommit);
        nodeObject.callbacks.onSizeChange = (event) => {
            invoke(event, originalCallbacks.onSizeChange, callbacks.onSizeChange, onSizeChange);
        };
        nodeObject.callbacks.onLinesChanged = (event) => {
            invoke(event, originalCallbacks.onLinesChanged, callbacks.onLinesChanged);
            lineList = [...event.lines];
        };
        lineList = nodeObject.getAllOutgoingLines();
        void tick().then(() => {
            if (mounted && nodeObject!.element) nodeObject!.remeasureDomGeometry();
        });
    });

    onDestroy(() => {
        mounted = false;
        nodeObject.callbacks.canStartDrag = originalCallbacks.canStartDrag;
        nodeObject.callbacks.resolveDragPosition = originalCallbacks.resolveDragPosition;
        nodeObject.callbacks.resolveSelectionMode = originalCallbacks.resolveSelectionMode;
        nodeObject.callbacks.onDragStart = originalCallbacks.onDragStart;
        nodeObject.callbacks.onDrag = originalCallbacks.onDrag;
        nodeObject.callbacks.onGeometryCommit = originalCallbacks.onGeometryCommit;
        nodeObject.callbacks.onSelectionChange = originalCallbacks.onSelectionChange;
        nodeObject.callbacks.onResizeHandleChange = originalCallbacks.onResizeHandleChange;
        nodeObject.callbacks.onLinesChanged = originalCallbacks.onLinesChanged;
        nodeObject.callbacks.onSizeChange = originalCallbacks.onSizeChange;
        if (ownsNode) {
            nodeObject.destroy(false);
        } else if (nodeDOM) {
            nodeObject.detachElement(nodeDOM);
        }
    });

    $effect(() => {
        const nextX = x;
        const nextY = y;
        if (!mounted) return;
        untrack(() => {
            nodeObject!.worldTransform = { x: nextX, y: nextY };
            nodeObject!.writeTransformAndLines();
        });
    });

    $effect(() => {
        const nextWidth = width;
        const nextHeight = height;
        if (!mounted) return;
        const object = untrack(() => nodeObject!);
        void tick().then(() => {
            if (!mounted || !object.element) return;
            if (nextWidth != null) object.element.style.width = `${nextWidth}px`;
            if (nextHeight != null) object.element.style.height = `${nextHeight}px`;
            if (nextWidth != null || nextHeight != null) {
                object.setSizeState(
                    nextWidth ?? object.hitBox.width,
                    nextHeight ?? object.hitBox.height,
                );
            }
            object.remeasureDomGeometry();
        });
    });

    export function getNodeObject() {
        return nodeObject;
    }
</script>


{#each lineList as line (line.lineId)}
    {@const LineFor = resolveLineComponent?.(line) ?? LineSvelteComponent}
    <LineFor {line} />
{/each}
<div
    {...elementProps}
    bind:this={nodeDOM}
    data-snapline-type="node"
    class={className}
    style="position: absolute; transform-origin: top left; will-change: transform;"
    style:width={width != null ? `${width}px` : undefined}
    style:height={height != null ? `${height}px` : undefined}
    transition:blur|global={{duration: 200}}
>
    {@render children()}
    {#each nodeObject.resizeHandles as handle}
        <div
            class="snapline-node-resize"
            data-snapline-part="node-resize"
            data-handle={handle}
            style:--snapline-resize-thickness={`${resizeHandleThickness ?? DEFAULT_RESIZE_HANDLE_THICKNESS}px`}
        ></div>
    {/each}
</div>


<style>
    .snapline-node-resize {
        position: absolute;
        pointer-events: none;
    }
    .snapline-node-resize[data-handle="n"],
    .snapline-node-resize[data-handle="s"] {
        right: var(--snapline-resize-thickness);
        left: var(--snapline-resize-thickness);
        height: var(--snapline-resize-thickness);
    }
    .snapline-node-resize[data-handle="e"],
    .snapline-node-resize[data-handle="w"] {
        top: var(--snapline-resize-thickness);
        bottom: var(--snapline-resize-thickness);
        width: var(--snapline-resize-thickness);
    }
    .snapline-node-resize[data-handle="n"],
    .snapline-node-resize[data-handle^="n"] { top: calc(var(--snapline-resize-thickness) / -2); }
    .snapline-node-resize[data-handle="s"],
    .snapline-node-resize[data-handle^="s"] { bottom: calc(var(--snapline-resize-thickness) / -2); }
    .snapline-node-resize[data-handle="e"],
    .snapline-node-resize[data-handle$="e"] { right: calc(var(--snapline-resize-thickness) / -2); }
    .snapline-node-resize[data-handle="w"],
    .snapline-node-resize[data-handle$="w"] { left: calc(var(--snapline-resize-thickness) / -2); }
    .snapline-node-resize[data-handle="ne"],
    .snapline-node-resize[data-handle="se"],
    .snapline-node-resize[data-handle="sw"],
    .snapline-node-resize[data-handle="nw"] {
        width: var(--snapline-resize-thickness);
        height: var(--snapline-resize-thickness);
    }
</style>
